use_frameworks!

target 'KoalaTeaVideo_Example' do
  pod 'KoalaTeaVideo', :path => '../'

  target 'KoalaTeaVideo_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 2.1.0'
    pod 'Nimble', '~> 8.0.2'
  end
end
