use_frameworks!

target 'koala-tea-video_Example' do
  pod 'koala-tea-video', :path => '../'

  target 'koala-tea-video_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 2.1.0'
    pod 'Nimble', '~> 8.0.2'
  end
end
