platform :ios, '10.3'

use_frameworks!

target 'KoalaTeaAssetPlayer_Example' do
  pod 'KoalaTeaAssetPlayer', :path => '../'

  target 'KoalaTeaAssetPlayer_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 2.1.0'
    pod 'Nimble', '~> 8.0.2'
  end
end
